
[project]
name = "package-0"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = ['requests (==2.32.5)', "napari (>=0.6.6,<0.7.0)"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
aiohttp = '>=3.13.2,<4.0.0'

[dependency-groups]
lint = [
    "flake8 (>=7.3.0,<8.0.0)",
]
db = [
    "sqlalchemy[asyncio] (>=2.0.44,<3.0.0) ; sys_platform == 'Darwin' or sys_platform == 'Windows'",
]
